# Generated by Django 5.2.3 on 2025-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_location_alter_tool_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
