# Generated by Django 5.2.3 on 2025-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
