# Generated by Django 5.2.3 on 2025-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tool_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='cloudinary_url',
        ),
    ]
