# Generated by Django 5.2.1 on 2025-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tool_remove_booking_room_booking_tool_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_images/'),
        ),
    ]
