# Generated by Django 5.2.3 on 2025-06-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_tool_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='old_location',
        ),
    ]
