# Generated by Django 5.2.3 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
