# Generated by Django 5.2.3 on 2025-06-27 16:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_tool_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
