# Generated by Django 5.2.3 on 2025-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_location_alter_tool_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
